---
- name: Install MySQL on Ubuntu
  hosts: 172.16.0.202 # Replace with your target host or group name
  become: yes  # This will enable sudo privileges for the tasks

  tasks:
    - name: Update apt cache
      apt-get:
        update_cache: yes
      become: yes

    - name: Install MySQL server and client
      apt-get:
        name: "{{ item }}"
        state: present
      become: yes
      loop:
        - mysql-server
        - mysql-client

    - name: Start MySQL service
      service:
        name: mysql
        state: started
      become: yes
